// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_7z3YiKExgBHywAPN-pZs_KUQt7EVKMI',
    appId: '1:208549941260:web:5e3c3235c6b421f4235e29',
    messagingSenderId: '208549941260',
    projectId: 'palvoice-database',
    authDomain: 'palvoice-database.firebaseapp.com',
    databaseURL: 'https://palvoice-database-default-rtdb.firebaseio.com',
    storageBucket: 'palvoice-database.appspot.com',
    measurementId: 'G-2XX27PSLTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGVsMakjylUdUWeT3R8POrdHAMkkd-Lq0',
    appId: '1:208549941260:android:c10ed3547d72090b235e29',
    messagingSenderId: '208549941260',
    projectId: 'palvoice-database',
    databaseURL: 'https://palvoice-database-default-rtdb.firebaseio.com',
    storageBucket: 'palvoice-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF3ROdfZlj8nDJF9Dwcne2JAR5zjszJOE',
    appId: '1:208549941260:ios:2616b5f6fdcab6e6235e29',
    messagingSenderId: '208549941260',
    projectId: 'palvoice-database',
    databaseURL: 'https://palvoice-database-default-rtdb.firebaseio.com',
    storageBucket: 'palvoice-database.appspot.com',
    iosBundleId: 'com.example.palvoice',
  );
}
